import { useState } from "react";
import { BOOKS_EDUCATION } from "../content/insights.js";
export default function AboutPreview(){
 const book=BOOKS_EDUCATION.find(i=>i.kind==="Book"),course=BOOKS_EDUCATION.find(i=>i.kind==="Course"),[open,setOpen]=useState(null);
 const toggle=p=>setOpen(open===p?null:p);
 return <section className="about section about-preview about-publishing" id="about">
  <div className="about-panel"><p className="eyebrow">ABOUT ALEX</p><div className="about-panel-body"><div className="about-portrait-wrap"><img className="about-portrait" src="/headshot.png" alt="Alex Kagianaris, Esq."/></div><div className="about-copy"><h2>Law, business<br/>and culture —<br/>viewed together.</h2><p className="about-lead">I'm a Senior Attorney at The Lew Firm APC, working across sports, NIL, entertainment and intellectual property.</p><button className="publishing-cta" type="button" onClick={()=>toggle("about")}>ABOUT ALEX <span>{open==="about"?"−":"→"}</span></button></div></div></div>
  <div className="book-panel"><p className="eyebrow">BOOK</p><div className="book-panel-body"><div className="book-object"><div className="book-spine"/><div className="book-cover"><span>SPORTS · LAW · POWER</span><strong>THE AUDIBLES<br/>THAT CHANGED<br/>SPORTS</strong><i>How Legal Fights Rewrote<br/>The Sports Industry</i><b>ALEX KAGIANARIS</b></div></div><div className="book-copy"><h3>{book?.title}</h3><p>How legal fights rewrote the sports industry. A trade nonfiction book about the legal moments that changed who held power, who got paid and how modern sports was built.</p><button className="publishing-cta" type="button" onClick={()=>toggle("book")}>LEARN MORE <span>{open==="book"?"−":"→"}</span></button></div></div></div>
  <div className="course-panel"><p className="eyebrow">COURSE</p><div className="course-panel-body"><div className="course-visual"><div className="course-screen"><span>NIL + TRANSFERS</span><strong>NIL + TRANSFERS</strong><i>PRACTICAL GUIDANCE<br/>REAL-WORLD SCENARIOS<br/>WHAT COMES NEXT</i></div><div className="course-keyboard"/></div><div className="course-copy"><h3>NIL + Transfers Course</h3><p>{course?.description}</p><button className="publishing-cta" type="button" onClick={()=>toggle("course")}>EXPLORE THE COURSE <span>{open==="course"?"−":"→"}</span></button></div></div></div>
  {open&&<div className="publishing-detail"><button className="publishing-detail-close" onClick={()=>setOpen(null)}>CLOSE ×</button>
   {open==="about"&&<><p className="eyebrow">ABOUT ALEX</p><h3>Attorney. Operator. Creator.</h3><p>Alex Kagianaris, Esq. is a Senior Attorney at The Lew Firm APC. His practice focuses on sports, NIL, entertainment, intellectual property, and the agreements and business decisions behind a career, brand or creative project.</p><p>Operating businesses and producing creative work also inform how he approaches rights, ownership, leverage and what a transaction makes possible next.</p><a href="mailto:ak@thelewfirm.com">CONTACT ALEX ↗</a></>}
   {open==="book"&&<><p className="eyebrow">FORTHCOMING BOOK</p><h3>The Audibles That Changed Sports</h3><p><em>How Legal Fights Rewrote The Sports Industry</em></p><p>A trade nonfiction book about the legal moments that reshaped sports. The law is the spine; the people and conflicts that changed the industry are the story.</p></>}
   {open==="course"&&<><p className="eyebrow">NIL + TRANSFERS COURSE</p><h3>Understand the rules before the decision.</h3><p>Practical guidance for athletes, families, lawyers and NIL agents navigating NIL agreements, transfers, financial-aid questions and the rules around them.</p><p>A structured public educational product with lessons, assessments and practical resources.</p></>}
  </div>}
 </section>
}